---
# handlers file for xray
- name: Restart xray
  become: true
  ansible.builtin.systemd:
    name: "{{ xray_daemon }}"
    state: restarted
  when:
    - xray_start_service

- name: Stop xray
  become: true
  ansible.builtin.systemd:
    name: "{{ xray_daemon }}"
    state: stopped
