# defaults file for artifactory_nginx_ssl

## For production deployments,You SHOULD change it.
# server_name: test.artifactory.com

nginx_daemon: nginx

redirect_http_to_https_enabled: true

nginx_worker_processes: 1
artifactory_docker_registry_subdomain: false

artifactory_conf_template: artifactory.conf.j2
nginx_conf_template: nginx.conf.j2

ssl_certificate_path: /etc/pki/tls/certs
ssl_certificate_key_path: /etc/pki/tls/private
